<?php /* @var \Zend\View\Renderer\PhpRenderer $this ; */ ?>
<!DOCTYPE html>

<!--[if IEMobile 7]><html class="no-js iem7 oldie"><![endif]-->
<!--[if (IE 7)&!(IEMobile)]><html class="no-js ie7 oldie" lang="en"><![endif]-->
<!--[if (IE 8)&!(IEMobile)]><html class="no-js ie8 oldie" lang="en"><![endif]-->
<!--[if (gt IE 8)|(gt IEMobile 7)]><!--><html class="no-js" lang="en"><!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <?php echo $this->headTitle('Starbound Log')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('HandheldFriendly', 'True')
        ->appendName('MobileOptimized', '320')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1')
        ->appendHttpEquiv('cleartype', 'on');
    ?>

    <?php echo $this->headLink(array(
        'rel'  => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/mws_admin/favicon.ico'))
        ->appendStylesheet($this->basePath() . '/mws_admin/css/reset.css?v=1', null, null, null)
        ->appendStylesheet($this->basePath() . '/mws_admin/css/style.css?v=1', null, null, null)
        ->appendStylesheet($this->basePath() . '/mws_admin/css/colors.css?v=1', null, null, null)
        ->appendStylesheet($this->basePath() . '/mws_admin/css/print.css?v=1', 'print', null, null)
        ->appendStylesheet($this->basePath() . '/mws_admin/css/480.css?v=1', 'only all and (min-width: 480px)', null, null)
        ->appendStylesheet($this->basePath() . '/mws_admin/css/768.css?v=1', 'only all and (min-width: 768px)', null, null)
        ->appendStylesheet($this->basePath() . '/mws_admin/css/992.css?v=1', 'only all and (min-width: 992px)', null, null)
        ->appendStylesheet($this->basePath() . '/mws_admin/css/1200.css?v=1', 'only all and (min-width: 1200)', null, null)
        ->appendStylesheet($this->basePath() . '/mws_admin/css/2x.css?v=1',
            'only all and (-webkit-min-device-pixel-ratio: 1.5), only screen and (-o-min-device-pixel-ratio: 3/2), only screen and (min-device-pixel-ratio: 1.5)', null, null)
        ->appendStylesheet($this->basePath() . 'http://fonts.googleapis.com/css?family=Open+Sans:300', null, null, null)
        ->appendStylesheet($this->basePath() . 'css/error.css?v=1', 'screen', null, null);
    ?>


    <?php echo $this->headScript()
        ->appendFile($this->basePath() . '/mws_admin/js/libs/modernizr.custom.js')
        ->appendFile($this->basePath() . '/mws_admin/js/libs/jquery-1.8.2.min.js')
        ->appendFile($this->basePath() . '/mws_admin/js/setup.js')
        ->appendFile($this->basePath() . '/mws_admin/js/html5shiv.js');
    ?>

</head>
<body class="clearfix">

<!-- Prompt IE 6 users to install Chrome Frame -->
<!--[if lt IE 7]><p class="message red-gradient simpler">Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

<div id="container">
    <div class="scratch-metal">
        <h1>404</h1>
        <h2>Page not found</h2>
    </div>
    <button class="button huge anthracite-gradient glossy full-width" id="button" onclick="window.history.back();">Back</button>
</div>


<!-- JavaScript at the bottom for fast page loading -->
<?php echo $this->inlineScript() ?>

</body>
</html>
