<?php
/* @var \Trks\View\TrksPhpRenderer $this */
/* @var \Trks\Form\Element\ButtonRow $element */
/* @var string $name */
/* @var array $buttons value, isSubmit, class */
?>
<?php
    $buttonsProcessed = [];
    foreach ($buttons as $key => $button) {
        if (!is_array($button)) {
            if (!is_numeric($key)) {
                $button = array(
                    'value' => $key,
                    'isSubmit' => $button
                );
            } else {
                $button = array(
                    'value' => $button
                );
            }
        } else if (!isset($button['value']) || !$button['value']) {
            throw new Exception('no name for button provided!');
        }
        if (!isset($button['isSubmit'])) {
            $button['isSubmit'] = in_array($button['value'], [ 'Submit', 'Send', 'Save', 'submit', 'send', 'save' ]);
        }
        if (!isset($button['style'])) {
            $button['style'] = '';
        }
        if (!isset($button['onClick'])) {
            $button['onClick'] = '';
            if ($button['isSubmit'] == -1) {
                if (StarboundLog\Model\ViewData::$formCancelUrl) {
                    $button['onClick'] = sprintf('location.href=\'%s\';', $this->escapeJs(StarboundLog\Model\ViewData::$formCancelUrl));
                } else {
                    $button['onClick'] = 'history.go(-1);';
                }
                $button['isSubmit'] = 0;
            }
        }
        if (!isset($button['class'])) {
            $button['class'] = $button['isSubmit'] ? 'btn btn-danger' : 'btn';
        }
        $buttonsProcessed[] = $button;
    }
?>
<?php foreach ($buttonsProcessed as $button): ?>
    <!--suppress HtmlFormInputWithoutLabel -->
    <input class="<?= $button['class'] ?>"
           type="<?= $button['isSubmit'] ? 'submit' : 'button' ?>"
           value="<?= $button['value'] ?>"
           name="<?= $name ?>"
           onClick="<?= $button['onClick'] ?>"
           style="<?= $button['style'] ?>">
<?php endforeach; ?>