<?php /* @var \Zend\View\Renderer\PhpRenderer $this ; */ ?>

<?= $this->render('_part/header.phtml'); ?>
<body>

<?php if (!\StarboundLog\Model\ViewData::$identity): ?>
    <div id="mws-login-ui" style="display: none;">

        <div id="mws-login-form">
            <form class="mws-form"
                  action="<?= $this->url('main', array('controller' => 'user', 'action' => 'login')) ?>" method="post">
                <div class="mws-form-row">
                    <div class="mws-form-item">
                        <input type="text" name="username" class="mws-login-username required" placeholder="username">
                    </div>
                </div>
                <div class="mws-form-row">
                    <div class="mws-form-item">
                        <input type="password" name="password" class="mws-login-password required"
                               placeholder="password">
                    </div>
                </div>
                <?= $this->formHidden(new \Zend\Form\Element\Csrf('csrf')) ?>
                <div class="mws-form-row">
                    <input type="submit" name="submit" value="Login" class="btn btn-success mws-login-button">

                    <p style="clear:both; margin:15px 0 0 0; color:#fff;">
                        Don't have an account?
                        <a href="<?= $this->url('main', array('controller' => 'user', 'action' => 'register')) ?>">Click here!</a>
                    </p>
                </div>
            </form>
        </div>
    </div>
<?php endif; ?>

<div id="mws-header" class="clearfix">
    <?php /* Logo Container */ ?>
    <div id="mws-logo-container">
        <?php /* Logo Wrapper, images put within this wrapper will always be vertically centered */ ?>
        <div id="mws-logo-wrap">
            <img src="/images/sb_log.png" alt="starbound log"/>
        </div>
    </div>

    <?php /* User Tools (notifications, logout, profile, change password) */ ?>
    <div id="mws-user-tools" class="clearfix">
        <?php /*
        <!-- Notifications -->
        <div id="mws-user-notif" class="mws-dropdown-menu">
            <a href="#" data-toggle="dropdown" class="mws-dropdown-trigger"><i class="icon-planet"></i></a>

            <!-- Unread notification count --><!--
            <span class="mws-dropdown-notif">0</span>-->

            <!-- Notifications dropdown -->
            <div class="mws-dropdown-box">
                <div class="mws-dropdown-content">
                    <ul class="mws-notifications">
                        <!-- Here goes all the messages -->
                    </ul>
                    <div class="mws-dropdown-viewall">
                        <a href="#">View All Notifications</a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Messages -->
        <div id="mws-user-message" class="mws-dropdown-menu">
            <a href="#" data-toggle="dropdown" class="mws-dropdown-trigger"><i class="icon-users"></i></a>

            <!-- Unred messages count --><!--
            <span class="mws-dropdown-notif">0</span>-->

            <!-- Messages dropdown -->
            <div class="mws-dropdown-box">
                <div class="mws-dropdown-content">
                    <ul class="mws-messages">
                        <!-- Here goes all the messages -->
                    </ul>
                    <div class="mws-dropdown-viewall">
                        <a href="#">View All Messages</a>
                    </div>
                </div>
            </div>
        </div>
        */
        ?>
        <?php /* User Information and functions section */ ?>
        <?php if (\StarboundLog\Model\ViewData::$identity): ?>
            <?php $identity = \StarboundLog\Model\ViewData::$identity; ?>
            <div id="mws-user-info" class="mws-inset">

                <?php /* User Photo */ ?>
                <div id="mws-user-photo">
                    <img src="/images/icon_user.png" alt="user"/>
                </div>

                <?php /* Username and Functions */ ?>
                <div id="mws-user-functions">
                    <div id="mws-username">Hello, <?= $identity->user_login; ?></div>
                    <ul>
                        <li><a href="<?= $this->url('main', array('controller' => 'user', 'action' => 'logout')) ?>">Logout</a></li>
                    </ul>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

<div id="mws-wrapper">
    <?php /* Necessary markup, do not remove */ ?>
    <div id="mws-sidebar-stitch"></div>
    <div id="mws-sidebar-bg"></div>

    <div id="mws-sidebar">

        <div id="mws-nav-collapse">
            <span></span>
            <span></span>
            <span></span>
        </div>

        <?php /*

        <div id="mws-searchbox" class="mws-inset">
            <form action="typography.html">
                <input type="text" class="mws-search-input" placeholder="Search..."/>
                <button type="submit" class="mws-search-submit"><i class="icon-search"></i></button>
            </form>
        </div>

        */
        ?>

        <div id="mws-navigation">
            <?php echo $this->navigation('navigation')->menu()->setPartial('_part/menu'); ?>
        </div>
    </div>

    <div id="mws-container" class="clearfix">
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <div id="mws-footer">
            <?php echo date('Y'); ?>
        </div>
    </div>

</div>

<?php echo $this->inlineScript() ?>

</body>
<?= '</html>' ?>
