<?php /* @var \Zend\View\Renderer\PhpRenderer $this ; */ ?>
<?= $this->render('_part/header.phtml'); ?>
<body>

<div id="mws-header" class="clearfix">
    <div id="mws-logo-container">
        <div id="mws-logo-wrap">
            <img src="/images/sb_log.png" alt="starbound log"/>
        </div>
    </div>
</div>

<div id="mws-container" class="clearfix">
    <div class="container">
        <?php echo $this->content; ?>
    </div>

    <div id="mws-footer">
        <?php echo date('Y'); ?>
    </div>
</div>

<!-- JavaScript at the bottom for fast page loading -->
<?php echo $this->inlineScript() ?>

</body>
<?= '</html>' ?>
