<?php
/* @var \Trks\View\TrksPhpRenderer $this */
/* @var \Trks\Struct\MessagesStruct $messages */
?>

<?php if (!empty($messages->errorList)): ?>
    <div class="mws-form-message error">
        <?php if (count($messages->errorList) == 1): ?>
            <?= $this->escapeHtml($messages->errorList[0]); ?>
        <?php else: ?>
            <ul>
                <?php foreach ($messages->errorList as $message): ?>
                    <li><?= $this->escapeHtml($message) ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php if (!empty($messages->warningList)): ?>
    <div class="mws-form-message warning">
        <?php if (count($messages->warningList) == 1): ?>
            <?= $this->escapeHtml($messages->warningList[0]); ?>
        <?php else: ?>
            <ul>
                <?php foreach ($messages->warningList as $message): ?>
                    <li><?= $this->escapeHtml($message) ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php if (!empty($messages->successList)): ?>
    <div class="mws-form-message success">
        <?php if (count($messages->successList) == 1): ?>
            <?= $this->escapeHtml($messages->successList[0]); ?>
        <?php else: ?>
            <ul>
                <?php foreach ($messages->successList as $message): ?>
                    <li><?= $this->escapeHtml($message) ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php if (!empty($messages->infoList)): ?>
    <div class="mws-form-message info">
        <?php if (count($messages->infoList) == 1): ?>
            <?= $this->escapeHtml($messages->infoList[0]); ?>
        <?php else: ?>
            <ul>
                <?php foreach ($messages->infoList as $message): ?>
                    <li><?= $this->escapeHtml($message) ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
<?php endif; ?>