<?php /* @var \Trks\View\TrksPhpRenderer $this */ ?>
<?php /* @var \Zend\Form\Form $form */ ?>
<?php $this->layout('_layout/no_header.phtml'); ?>

<div id="mws-login-wrapper">
    <div id="mws-login">
        <h1>Login</h1>

        <div class="mws-login-lock"><i class="icon-lock"></i></div>
        <div id="mws-login-form">
            <form class="mws-form" action="" method="post">
                <?= $this->messages()->render(); ?>
                <div class="mws-form-row">
                    <div class="mws-form-item">
                        <?= $this->formElement($form->get('username')) ?>
                    </div>
                </div>
                <div class="mws-form-row">
                    <div class="mws-form-item">
                        <?= $this->formElement($form->get('password')) ?>
                    </div>
                </div>
                <?= $this->formElement($form->get('csrf')) ?>
                <div class="mws-form-row">
                    <input type="submit" value="Login" class="btn btn-success mws-login-button" style="width: 47%" name="submit">
                    <input type="submit" value="Cancel" class="btn btn-danger mws-login-button" style="width: 47%" onClick="location.href='<?= $this->url('main') ?>'; return false;" name="submit">
                    <p style="clear:both; margin:15px 0 0 0; color:#fff;">Don't have an account? <a href="<?= $this->url('main', array('controller'=>'user','action'=>'register')) ?>">Click here!</a></p>
                </div>
            </form>
        </div>
    </div>
</div>