<?php /* @var \Trks\View\TrksPhpRenderer $this */ ?>
<?php /* @var \Zend\Form\Form $form */ ?>
<?php $this->layout('_layout/no_header.phtml'); ?>

<div id="mws-login-wrapper">
    <div id="mws-login">
        <h1>Login</h1>

        <div class="mws-login-lock"><i class="icon-lock"></i></div>
        <div id="mws-login-form">
            <form class="mws-form" action="" method="post">
                <!--<div class="mws-form-message error">
                    The username or password you have entered is incorrect.
                </div>-->
                <?= $this->messages(\StarboundLog\Model\ViewData::getMessages()) ?>
                <div class="mws-form-row">
                    <div class="mws-form-item">
                        <?= $this->formElement($form->get('username')) ?>
                        <!-- <input type="text" name="username" class="mws-login-username required" placeholder="username"> !-->
                    </div>
                </div>
                <div class="mws-form-row">
                    <div class="mws-form-item">
                        <?= $this->formElement($form->get('password')) ?>
                        <!-- <input type="password" name="password" class="mws-login-password required"
                               placeholder="password"> !-->
                    </div>
                </div>
                <?php /*<div id="mws-login-remember" class="mws-form-row mws-inset">
                    <ul class="mws-form-list inline">
                        <li>
                            <input id="remember" type="checkbox">
                            <label for="remember">Remember me</label>
                        </li>
                    </ul>
                </div>*/?>
                <div class="mws-form-row">
                    <input type="submit" value="Login" class="btn btn-success mws-login-button" style="width: 47%" name="submit">
                    <input type="submit" value="Cancel" class="btn btn-danger mws-login-button" style="width: 47%" onClick="location.href='<?= $this->url('main') ?>'; return false;" name="submit">
                    <p style="clear:both; margin:15px 0 0 0; color:#fff;">Don't have an account? <a href="#">Click here!</a></p>
                </div>
            </form>
        </div>
    </div>
</div>