<?php

namespace StarboundLog\Model\Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\LockMode;

/**
 * PlanetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetsRepository extends EntityRepository
{
    /**
     * @inheritdoc
     *
     * @return \StarboundLog\Model\Entities\Planets[]
     */
    public function findAll()
    {
        return parent::findAll();
    }

    /**
     * @inheritdoc
     * @param array $criteria
     * @param array $orderBy
     * @param null  $limit
     * @param null  $offset
     *
     * @return \StarboundLog\Model\Entities\Planets[]
     */
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    /**
     * @inheritdoc
     * @param mixed $id
     * @param int   $lockMode
     * @param null  $lockVersion
     *
     * @return \StarboundLog\Model\Entities\Planets
     */
    public function find($id, $lockMode = LockMode::NONE, $lockVersion = null)
    {
        return parent::find($id, $lockMode, $lockVersion);
    }

    /**
     * @inheritdoc
     * @param array $criteria
     * @param array $orderBy
     *
     * @return \StarboundLog\Model\Entities\Planets
     */
    public function findOneBy(array $criteria, array $orderBy = null)
    {
        return parent::findOneBy($criteria, $orderBy);
    }
}
